site_name: Elevate
nav:
    - Home: index.md
    - Experiment: experiment.md
    - Weaknesses: weaknesses.md
    - Coverage metric: coverage.md
    - Effectiveness: effectiveness.md
    - Case study: case_study.md